# Generated by Django 6.0.4 on 2026-04-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_profile_following_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics/'),
        ),
    ]
