# Generated by Django 6.0.4 on 2026-06-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', '公開'), ('mutual_only', '相互フォローのみ')], default='public', max_length=20),
        ),
    ]
